CREATE TABLE IF NOT EXISTS `gyt_partner_campaign` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    `owner_id` BIGINT NOT NULL COMMENT '活动归属合作伙伴用户ID',
    `share_code` VARCHAR(32) NOT NULL COMMENT '公开分享码',
    `store_name` VARCHAR(100) NOT NULL COMMENT '门店名称',
    `city` VARCHAR(50) DEFAULT NULL COMMENT '城市',
    `phone` VARCHAR(30) DEFAULT NULL COMMENT '门店电话',
    `address` VARCHAR(255) DEFAULT NULL COMMENT '门店地址',
    `title` VARCHAR(120) NOT NULL COMMENT '活动标题',
    `subtitle` VARCHAR(255) DEFAULT NULL COMMENT '活动副标题',
    `price` DECIMAL(12,2) DEFAULT 0.00 COMMENT '报名价',
    `benefit_text` TEXT COMMENT '活动权益',
    `gift_text` TEXT COMMENT '到店赠品或体验说明',
    `share_reward_text` TEXT COMMENT '分享奖励说明',
    `quota` INT DEFAULT 0 COMMENT '名额，0表示不限',
    `signed_count` INT DEFAULT 0 COMMENT '已报名数量',
    `poster_image` VARCHAR(255) DEFAULT NULL COMMENT '活动主图',
    `status` TINYINT DEFAULT 1 COMMENT '状态: 0-下架 1-上架',
    `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted` TINYINT DEFAULT 0 COMMENT '逻辑删除',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_share_code` (`share_code`),
    INDEX `idx_owner_id` (`owner_id`),
    INDEX `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='合作伙伴裂变活动表';

CREATE TABLE IF NOT EXISTS `gyt_campaign_signup` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    `campaign_id` BIGINT NOT NULL COMMENT '活动ID',
    `owner_id` BIGINT NOT NULL COMMENT '活动归属合作伙伴用户ID',
    `user_id` BIGINT DEFAULT NULL COMMENT '已登录用户ID',
    `mobile` VARCHAR(20) NOT NULL COMMENT '报名手机号',
    `nickname` VARCHAR(50) DEFAULT NULL COMMENT '报名昵称',
    `order_sn` VARCHAR(64) NOT NULL COMMENT '活动报名单号',
    `amount` DECIMAL(12,2) DEFAULT 0.00 COMMENT '报名金额',
    `voucher_code` VARCHAR(64) NOT NULL COMMENT '核销码',
    `status` TINYINT DEFAULT 0 COMMENT '状态: 0-待支付/待确认 1-待核销 2-已核销 3-已取消',
    `remark` VARCHAR(500) DEFAULT NULL COMMENT '备注',
    `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted` TINYINT DEFAULT 0 COMMENT '逻辑删除',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_order_sn` (`order_sn`),
    UNIQUE KEY `uk_voucher_code` (`voucher_code`),
    INDEX `idx_campaign_id` (`campaign_id`),
    INDEX `idx_owner_id` (`owner_id`),
    INDEX `idx_mobile` (`mobile`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='合作伙伴活动报名与核销表';
